import { BuildInput, componentName, esc, Files, ns, strokeSteps } from './common'

const camelName = (b: BuildInput) => ns(b).replace(/-([a-z0-9])/g, (_m, c) => c.toUpperCase())

export function iconsTs(b: BuildInput): string {
  const n = ns(b)
  const entries = b.icons
    .map((i) => {
      const data = { viewBox: i.viewBox, width: i.width, height: i.height, kind: i.kind, category: i.category.join('/'), body: i.body }
      return `  ${esc(i.name)}: ${JSON.stringify(data)}`
    })
    .join(',\n')
  return `// Generated by Icon Library Toolkit — ${b.generatedAt}. Do not edit by hand.
export interface ${componentName(b)}Data {
  viewBox: string;
  width: number;
  height: number;
  kind: 'filled' | 'stroked' | 'multicolor' | 'mixed';
  /** category path from Figma (name path, section, frame or page), '' when none */
  category: string;
  /** inner SVG markup (themeable through --${n}-icon-* CSS variables) */
  body: string;
}

export const ${n.toUpperCase().replace(/-/g, '_')}_ICONS = {
${entries}
} as const;

export type ${componentName(b)}Name = keyof typeof ${n.toUpperCase().replace(/-/g, '_')}_ICONS;

/** Renamed icons: the old name still works for one major version and resolves to the new one. */
export const ${n.toUpperCase().replace(/-/g, '_')}_DEPRECATED = ${JSON.stringify(Object.fromEntries((b.release?.deprecated ?? []).map((d) => [d.name, d.replacedBy])), null, 2)} as const;
export type ${componentName(b)}DeprecatedName = keyof typeof ${n.toUpperCase().replace(/-/g, '_')}_DEPRECATED;

/** Stroke policy chosen in the plugin: 'constant' | 'scale' | 'table' (px weight by rendered size) */
export const ${n.toUpperCase().replace(/-/g, '_')}_STROKE: { policy: 'constant' | 'scale' | 'table'; table: readonly (readonly [number, number])[] } = { policy: '${b.settings.strokePolicy}', table: ${JSON.stringify(strokeSteps(b).map((s) => [s.size, s.weight]))} };

/** Stroke weight for a rendered size (px), or null when the policy has no size-dependent weight. */
export function ${camelName(b)}StrokeFor(size: number | string | undefined): number | null {
  if (${n.toUpperCase().replace(/-/g, '_')}_STROKE.policy !== 'table' || size === undefined || size === '') return null;
  const px = typeof size === 'number' ? size : parseFloat(size);
  if (!isFinite(px) || /em|%/.test(String(size))) return null;
  let w: number | null = null;
  for (const [s, weight] of ${n.toUpperCase().replace(/-/g, '_')}_STROKE.table) { if (w === null || s <= px) w = weight; }
  return w;
}

/** icon names grouped by category */
export const ${n.toUpperCase().replace(/-/g, '_')}_CATEGORIES: Record<string, ${componentName(b)}Name[]> = ${JSON.stringify(Object.fromEntries([...new Set(b.icons.map((i) => i.category.join('/')).filter(Boolean))].map((c) => [c, b.icons.filter((i) => i.category.join('/') === c).map((i) => i.name)])), null, 2)};

export const ${n.toUpperCase().replace(/-/g, '_')}_ICON_NAMES = Object.keys(${n.toUpperCase().replace(/-/g, '_')}_ICONS) as ${componentName(b)}Name[];
`
}

function names(b: BuildInput) {
  const n = ns(b)
  const C = componentName(b)
  const K = n.toUpperCase().replace(/-/g, '_')
  return { n, C, K }
}

function modern(b: BuildInput): string {
  const { n, C, K } = names(b)
  return `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { ${K}_DEPRECATED, ${K}_ICONS, ${C}Data, ${C}DeprecatedName, ${C}Name, ${camelName(b)}StrokeFor } from './icons';

/**
 * <${n}-icon name="…" />   (Angular 17.1+, standalone, signals)
 * Customise via inputs or CSS variables: --${n}-icon-size, --${n}-icon-color, --${n}-icon-color-2, --${n}-icon-stroke-width.
 * Pass [label] for meaningful icons; without it the icon is decorative (aria-hidden).
 */
@Component({
  selector: '${n}-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[attr.role]': 'label() ? "img" : null',
    '[attr.aria-label]': 'label() || null',
    '[attr.aria-hidden]': 'label() ? null : "true"',
    '[style.--${n}-icon-size]': 'sizeCss()',
    '[style.--${n}-icon-color]': 'color() || null',
    '[style.--${n}-icon-stroke-width]': 'strokeCss()'
  },
  template: '<span class="${n}-icon__inner" [innerHTML]="html()"></span>',
  styles: [
    ':host{display:inline-block;width:var(--${n}-icon-size,1em);height:var(--${n}-icon-size,1em);flex:none;line-height:0;vertical-align:-0.125em}',
    '.${n}-icon__inner{display:block;width:100%;height:100%}'
  ]
})
export class ${C} {
  private readonly sanitizer = inject(DomSanitizer);

  readonly name = input.required<${C}Name | ${C}DeprecatedName>();
  readonly size = input<string | number | undefined>(undefined);
  readonly color = input<string | undefined>(undefined);
  readonly strokeWidth = input<number | string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);

  protected readonly sizeCss = computed(() => {
    const s = this.size();
    return s === undefined || s === '' ? null : typeof s === 'number' ? s + 'px' : s;
  });

  /** explicit strokeWidth wins; otherwise the plugin's weight-by-size table (when that policy is used) */
  protected readonly strokeCss = computed(() => this.strokeWidth() ?? ${camelName(b)}StrokeFor(this.size()));

  protected readonly html = computed(() => {
    const requested = this.name();
    const name = (${K}_DEPRECATED as Record<string, string>)[requested] ?? requested;
    const data = (${K}_ICONS as Record<string, ${C}Data>)[name];
    if (!data) return '';
    // Trusted, generated markup (not user input).
    return this.sanitizer.bypassSecurityTrustHtml(
      '<svg viewBox="' + data.viewBox + '" width="100%" height="100%" fill="none" focusable="false" aria-hidden="true">' + data.body + '</svg>'
    );
  });
}
`
}

function classic(b: BuildInput): string {
  const { n, C, K } = names(b)
  return `import { ChangeDetectionStrategy, Component, HostBinding, Input, OnChanges } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { ${K}_DEPRECATED, ${K}_ICONS, ${C}Data, ${C}DeprecatedName, ${C}Name, ${camelName(b)}StrokeFor } from './icons';

/**
 * <${n}-icon name="…"></${n}-icon>   (Angular 14+, standalone, classic @Input)
 * Customise via inputs or CSS variables: --${n}-icon-size, --${n}-icon-color, --${n}-icon-color-2, --${n}-icon-stroke-width.
 * Pass [label] for meaningful icons; without it the icon is decorative (aria-hidden).
 */
@Component({
  selector: '${n}-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<span class="${n}-icon__inner" [innerHTML]="html"></span>',
  styles: [
    ':host{display:inline-block;width:var(--${n}-icon-size,1em);height:var(--${n}-icon-size,1em);flex:none;line-height:0;vertical-align:-0.125em}',
    '.${n}-icon__inner{display:block;width:100%;height:100%}'
  ]
})
export class ${C} implements OnChanges {
  @Input() name!: ${C}Name | ${C}DeprecatedName;
  @Input() size?: string | number;
  @Input() color?: string;
  @Input() strokeWidth?: number | string;
  @Input() label?: string;

  html: SafeHtml = '';

  constructor(private readonly sanitizer: DomSanitizer) {}

  @HostBinding('attr.role') get role(): string | null { return this.label ? 'img' : null; }
  @HostBinding('attr.aria-label') get ariaLabel(): string | null { return this.label || null; }
  @HostBinding('attr.aria-hidden') get ariaHidden(): string | null { return this.label ? null : 'true'; }
  @HostBinding('style.--${n}-icon-size') get sizeVar(): string | null {
    return this.size === undefined || this.size === '' ? null : typeof this.size === 'number' ? this.size + 'px' : this.size;
  }
  @HostBinding('style.--${n}-icon-color') get colorVar(): string | null { return this.color || null; }
  @HostBinding('style.--${n}-icon-stroke-width') get strokeVar(): string | number | null {
    return this.strokeWidth !== undefined ? this.strokeWidth : ${camelName(b)}StrokeFor(this.size);
  }

  ngOnChanges(): void {
    const name = (${K}_DEPRECATED as Record<string, string>)[this.name] ?? this.name;
    const data = (${K}_ICONS as Record<string, ${C}Data>)[name];
    // Trusted, generated markup (not user input).
    this.html = data
      ? this.sanitizer.bypassSecurityTrustHtml(
          '<svg viewBox="' + data.viewBox + '" width="100%" height="100%" fill="none" focusable="false" aria-hidden="true">' + data.body + '</svg>'
        )
      : '';
  }
}
`
}

function readme(b: BuildInput, flavour: 'modern' | 'classic'): string {
  const { n, C } = names(b)
  const range = flavour === 'modern' ? 'Angular 17.1 or newer (signal inputs)' : 'Angular 14 or newer (standalone + @Input)'
  return `# ${n} icons — Angular (${flavour})

Supports ${range}. No FontAwesome or other dependency.

## Use
\`\`\`ts
import { ${C} } from './${n}-icons/${flavour === 'modern' ? 'angular' : 'angular-classic'}';

@Component({ standalone: true, imports: [${C}], template: \`<${n}-icon name="${b.icons[0]?.name ?? 'name'}" />\` })
\`\`\`

Inputs: \`name\` (typed), \`size\`, \`color\`, \`strokeWidth\`, \`label\`.
CSS variables: \`--${n}-icon-size\`, \`--${n}-icon-color\`, \`--${n}-icon-color-2…\`, \`--${n}-icon-stroke-width\`.

Icons: ${b.icons.length}. See \`icons.ts\` for the typed list (\`${C}Name\`).
`
}

export function angularFiles(b: BuildInput, flavour: 'modern' | 'classic'): Files {
  const dir = flavour === 'modern' ? 'angular' : 'angular-classic'
  const { n, C } = names(b)
  return {
    [`${dir}/icons.ts`]: iconsTs(b),
    [`${dir}/${n}-icon.component.ts`]: flavour === 'modern' ? modern(b) : classic(b),
    [`${dir}/index.ts`]: `export * from './icons';\nexport { ${C} } from './${n}-icon.component';\n`,
    [`${dir}/README.md`]: readme(b, flavour)
  }
}
