import { Icon } from '../../types'
import { BuildInput, esc, Files, ns } from './common'

/**
 * Code Connect (HTML parser) templates: one figma.connect() per icon component, so Dev Mode and the Figma MCP server
 * show <ds-icon name="…"> for the icon and for icons nested in other components.
 * Publishing needs an Organization/Enterprise plan: `npx figma connect publish`.
 */

/** https://www.figma.com/design/<key>/<name>?node-id=1-2 from any figma.com file URL */
export function nodeUrl(fileUrl: string, nodeId: string): string | null {
  const m = /^(https:\/\/(?:www\.)?figma\.com\/(?:design|file)\/[A-Za-z0-9]+(?:\/[^?#]*)?)/.exec(fileUrl.trim())
  if (!m) return null
  return `${m[1]}?node-id=${nodeId.replace(':', '-')}`
}

const connectable = (i: Icon) => (i.sourceKind === 'component' || i.sourceKind === 'component-set') && /^\d+:\d+$/.test(i.nodeId)

export function codeConnectFiles(b: BuildInput): Files {
  const n = ns(b)
  const url = b.settings.codeConnectUrl
  const base = url && nodeUrl(url, '0:1') ? url : ''
  const ok = b.icons.filter(connectable)
  const skipped = b.icons.length - ok.length
  const blocks = ok
    .map((i) => {
      const target = base ? nodeUrl(base, i.nodeId)! : `FILE_URL?node-id=${i.nodeId.replace(':', '-')}`
      return `figma.connect(${esc(target)}, {
  example: () => html\`<${n}-icon name=${esc(i.name)}></${n}-icon>\`
})`
    })
    .join('\n\n')
  const src = `// Generated by Icon Library Toolkit — ${b.generatedAt}. Do not edit by hand.
// Code Connect (HTML parser): maps each icon component to <${n}-icon name="…">.
import figma, { html } from '@figma/code-connect/html'

${blocks || '// No component-based icons to connect.'}
`
  const readme = `# Code Connect for ${n} icons

${ok.length} icon component${ok.length === 1 ? '' : 's'} mapped${skipped ? `; ${skipped} skipped (not a plain component: instances, frames and loose layers have no component node id)` : ''}.
${base ? '' : '\n**Set the Figma file URL** in the plugin (Settings → Team config → Figma file URL) and export again, or replace `FILE_URL` in `' + n + '-icons.figma.ts`.\n'}
1. Install: \`npm i -D @figma/code-connect\`
2. Copy \`figma.config.json\` and \`${n}-icons.figma.ts\` into your repo.
3. Publish (Organization or Enterprise plan): \`npx figma connect publish\`

The mapping targets the \`<${n}-icon>\` custom element (the Web Component output, or any element that takes \`name\`). For Angular, the same tag works with the Angular component.
`
  return {
    [`code-connect/${n}-icons.figma.ts`]: src,
    'code-connect/figma.config.json': JSON.stringify({ codeConnect: { parser: 'html', include: [`${n}-icons.figma.ts`] } }, null, 2) + '\n',
    'code-connect/README.md': readme
  }
}
