import { Icon } from '../../types'
import { BuildInput, categoryId, componentName, constName, esc, Files, ns, strokeSteps } from './common'

/**
 * Framework-neutral icon data, shared by the Angular and React outputs:
 *   icon-data.ts      types, names, deprecated aliases, stroke helper (type-only + tiny values)
 *   icons/<name>.ts   one export per icon (import only what you use: tree-shakable)
 *   icons/index.ts    barrel of the above
 *   icons.ts          every icon in one map (back-compat, `provideAllIcons`)
 *   loaders.ts        category → dynamic import, so icons used by name load in per-category chunks
 */

export const camelNs = (b: BuildInput) => ns(b).replace(/-([a-z0-9])/g, (_m, c) => c.toUpperCase())
export const K = (b: BuildInput) => ns(b).toUpperCase().replace(/-/g, '_')

const catSlug = (icon: Icon) => categoryId(icon).replace(/\//g, '-') || '_uncategorised'

export function categoryGroups(b: BuildInput): Map<string, Icon[]> {
  const by = new Map<string, Icon[]>()
  for (const i of b.icons) {
    const s = catSlug(i)
    by.set(s, [...(by.get(s) ?? []), i])
  }
  return by
}

function iconDataTs(b: BuildInput): string {
  const n = ns(b)
  const C = componentName(b)
  const k = K(b)
  const names = b.icons.map((i) => esc(i.name)).join(' | ') || 'never'
  const cat = Object.fromEntries(b.icons.map((i) => [i.name, catSlug(i)]))
  return `// Generated by Icon Library Toolkit — ${b.generatedAt}. Do not edit by hand.
export interface ${C}Data {
  /** icon name, the key used by \`name="…"\` */
  name: string;
  viewBox: string;
  width: number;
  height: number;
  kind: 'filled' | 'stroked' | 'multicolor' | 'mixed';
  /** category path from Figma (name path, section, frame or page), '' when none */
  category: string;
  /** inner SVG markup (themeable through --${n}-icon-* CSS variables) */
  body: string;
}

export type ${C}Name = ${names};

/** Renamed icons: the old name still works for one major version and resolves to the new one. */
export const ${k}_DEPRECATED = ${JSON.stringify(Object.fromEntries((b.release?.deprecated ?? []).map((d) => [d.name, d.replacedBy])), null, 2)} as const;
export type ${C}DeprecatedName = keyof typeof ${k}_DEPRECATED;

/** icon name → category chunk (see loaders.ts) */
export const ${k}_CATEGORY_OF: Readonly<Record<string, string>> = ${JSON.stringify(cat)};

/** Stroke policy chosen in the plugin: 'constant' | 'scale' | 'table' (px weight by rendered size) */
export const ${k}_STROKE: { policy: 'constant' | 'scale' | 'table'; table: readonly (readonly [number, number])[] } = { policy: '${b.settings.strokePolicy}', table: ${JSON.stringify(strokeSteps(b).map((s) => [s.size, s.weight]))} };

/** Stroke weight for a rendered size (px), or null when the policy has no size-dependent weight. */
export function ${camelNs(b)}StrokeFor(size: number | string | undefined): number | null {
  if (${k}_STROKE.policy !== 'table' || size === undefined || size === '') return null;
  const px = typeof size === 'number' ? size : parseFloat(size);
  if (!isFinite(px) || /em|%/.test(String(size))) return null;
  let w: number | null = null;
  for (const [s, weight] of ${k}_STROKE.table) { if (w === null || s <= px) w = weight; }
  return w;
}

/** Final markup for one icon (shared by every component). */
export function ${camelNs(b)}Svg(data: ${C}Data): string {
  return '<svg viewBox="' + data.viewBox + '" width="100%" height="100%" fill="none" focusable="false" aria-hidden="true">' + data.body + '</svg>';
}
`
}

function oneIcon(b: BuildInput, i: Icon): string {
  const C = componentName(b)
  const data = { name: i.name, viewBox: i.viewBox, width: i.width, height: i.height, kind: i.kind, category: i.category.join('/'), body: i.body }
  return `// Generated by Icon Library Toolkit. Do not edit by hand.
import type { ${C}Data } from '../icon-data';

export const ${constName(b, i)}: ${C}Data = ${JSON.stringify(data)};
`
}

function iconsTs(b: BuildInput): string {
  const C = componentName(b)
  const k = K(b)
  const imports = b.icons.map((i) => `import { ${constName(b, i)} } from './icons/${i.name}';`).join('\n')
  const entries = b.icons.map((i) => `  ${esc(i.name)}: ${constName(b, i)}`).join(',\n')
  const cats = Object.fromEntries([...new Set(b.icons.map((i) => categoryId(i)).filter(Boolean))].map((c) => [c, b.icons.filter((i) => categoryId(i) === c).map((i) => i.name)]))
  return `// Generated by Icon Library Toolkit — ${b.generatedAt}. Do not edit by hand.
// Every icon in one map. Importing this file pulls ALL icons into your bundle; to ship only some, import them from './icons' one by one.
import type { ${C}Data, ${C}Name } from './icon-data';
export * from './icon-data';
${imports}

export const ${k}_ICONS: Readonly<Record<${C}Name, ${C}Data>> = {
${entries}
};

/** icon names grouped by category */
export const ${k}_CATEGORIES: Record<string, ${C}Name[]> = ${JSON.stringify(cats, null, 2)};

export const ${k}_ICON_NAMES = Object.keys(${k}_ICONS) as ${C}Name[];
`
}

function loadersTs(b: BuildInput): string {
  const C = componentName(b)
  const k = K(b)
  const groups = categoryGroups(b)
  const lines = [...groups.keys()].map((s) => `  ${esc(s)}: () => import('./categories/${s}').then((m) => m.default)`).join(',\n')
  return `// Generated by Icon Library Toolkit. Do not edit by hand.
import type { ${C}Data } from './icon-data';

/** One dynamic import per category: bundlers emit a lazy chunk each, loaded the first time an icon of that category is used by name. */
export const ${k}_LOADERS: Readonly<Record<string, () => Promise<readonly ${C}Data[]>>> = {
${lines}
};
`
}

export function iconDataFiles(b: BuildInput, dir: string): Files {
  const C = componentName(b)
  const out: Files = {
    [`${dir}/icon-data.ts`]: iconDataTs(b),
    [`${dir}/icons.ts`]: iconsTs(b),
    [`${dir}/loaders.ts`]: loadersTs(b),
    [`${dir}/icons/index.ts`]: `// Generated by Icon Library Toolkit. Do not edit by hand.\n${b.icons.map((i) => `export { ${constName(b, i)} } from './${i.name}';`).join('\n')}\n`
  }
  for (const i of b.icons) out[`${dir}/icons/${i.name}.ts`] = oneIcon(b, i)
  for (const [slug, icons] of categoryGroups(b)) {
    out[`${dir}/categories/${slug}.ts`] = `// Generated by Icon Library Toolkit. Do not edit by hand.
import type { ${C}Data } from '../icon-data';
${icons.map((i) => `import { ${constName(b, i)} } from '../icons/${i.name}';`).join('\n')}

export default [${icons.map((i) => constName(b, i)).join(', ')}] as readonly ${C}Data[];
`
  }
  return out
}
