import { BuildInput, esc, Files, ns, strokeSteps } from './common'
import { camelNs, K } from './icondata'

/**
 * Framework-free custom element: <ds-icon name="home" size="24" color="#0a7d3b" label="Home"></ds-icon>
 * Plain ES module (no build step needed) + .d.ts. Theming goes through CSS variables, which inherit into the shadow root.
 */
export function webComponentFiles(b: BuildInput): Files {
  const n = ns(b)
  const k = K(b)
  const c = camelNs(b)
  const tag = `${n}-icon`
  const entries = b.icons
    .map((i) => `  ${esc(i.name)}: ${JSON.stringify({ viewBox: i.viewBox, body: i.body, category: i.category.join('/') })}`)
    .join(',\n')
  const dep = JSON.stringify(Object.fromEntries((b.release?.deprecated ?? []).map((d) => [d.name, d.replacedBy])))
  const table = b.settings.strokePolicy === 'table' ? JSON.stringify(strokeSteps(b).map((x) => [x.size, x.weight])) : '[]'

  const js = `// Generated by Icon Library Toolkit — ${b.generatedAt}. Do not edit by hand.
// <${tag} name="…" size="24" color="#0a7d3b" stroke-width="1.5" label="Accessible name"></${tag}>

export const ${k}_ICONS = {
${entries}
};

export const ${k}_DEPRECATED = ${dep};
const STROKE_POLICY = '${b.settings.strokePolicy}';
const STROKE_TABLE = ${table};

const strokeFor = (size) => {
  if (STROKE_POLICY !== 'table' || !size) return null;
  const px = parseFloat(size);
  if (!isFinite(px) || /em|%/.test(size)) return null;
  let w = null;
  for (const [s, weight] of STROKE_TABLE) { if (w === null || s <= px) w = weight; }
  return w;
};

const STYLE = ':host{display:inline-block;width:var(--${n}-icon-size,1em);height:var(--${n}-icon-size,1em);flex:none;line-height:0;vertical-align:-0.125em}svg{display:block;width:100%;height:100%}';

export class ${camelToPascal(c)}IconElement extends HTMLElement {
  static get observedAttributes() { return ['name', 'size', 'color', 'stroke-width', 'label']; }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() { this.#render(); }
  attributeChangedCallback() { if (this.isConnected) this.#render(); }

  /** add or replace icons at runtime: { 'my-icon': { viewBox: '0 0 24 24', body: '<path d="…"/>' } } */
  static register(icons) { Object.assign(${k}_ICONS, icons); }

  #render() {
    const requested = this.getAttribute('name') || '';
    const data = ${k}_ICONS[${k}_DEPRECATED[requested] || requested];
    const size = this.getAttribute('size');
    const color = this.getAttribute('color');
    const label = this.getAttribute('label');
    const weight = this.getAttribute('stroke-width') ?? strokeFor(size);
    if (size) this.style.setProperty('--${n}-icon-size', /^[0-9.]+$/.test(size) ? size + 'px' : size); else this.style.removeProperty('--${n}-icon-size');
    if (color) this.style.setProperty('--${n}-icon-color', color); else this.style.removeProperty('--${n}-icon-color');
    if (weight !== null && weight !== undefined && weight !== '') this.style.setProperty('--${n}-icon-stroke-width', String(weight)); else this.style.removeProperty('--${n}-icon-stroke-width');
    if (label) { this.setAttribute('role', 'img'); this.setAttribute('aria-label', label); this.removeAttribute('aria-hidden'); }
    else { this.removeAttribute('role'); this.removeAttribute('aria-label'); this.setAttribute('aria-hidden', 'true'); }
    // Trusted, generated markup (not user input).
    this.shadowRoot.innerHTML = '<style>' + STYLE + '</style>' + (data
      ? '<svg viewBox="' + data.viewBox + '" fill="none" focusable="false" aria-hidden="true">' + data.body + '</svg>'
      : '');
  }
}

if (!customElements.get('${tag}')) customElements.define('${tag}', ${camelToPascal(c)}IconElement);
`
  const dts = `// Generated by Icon Library Toolkit. Do not edit by hand.
export type ${camelToPascal(c)}IconName = ${b.icons.map((i) => esc(i.name)).join(' | ') || 'never'};
export interface ${camelToPascal(c)}IconData { viewBox: string; body: string; category?: string }
export declare const ${k}_ICONS: Record<${camelToPascal(c)}IconName, ${camelToPascal(c)}IconData>;
export declare const ${k}_DEPRECATED: Record<string, string>;
export declare class ${camelToPascal(c)}IconElement extends HTMLElement {
  static register(icons: Record<string, ${camelToPascal(c)}IconData>): void;
  name: string | null;
}
declare global {
  interface HTMLElementTagNameMap { '${tag}': ${camelToPascal(c)}IconElement }
}
`
  const first = b.icons[0]?.name ?? 'name'
  const readme = `# ${n} icons — Web Component

A framework-free custom element. Works in plain HTML, Vue, Svelte, Lit, Angular (with \`CUSTOM_ELEMENTS_SCHEMA\`) and React.

\`\`\`html
<script type="module" src="./${n}-icon.js"></script>
<${tag} name="${first}" size="24" color="#0a7d3b" label="${first}"></${tag}>
\`\`\`

Attributes: \`name\`, \`size\` (number = px or any CSS length), \`color\`, \`stroke-width\`, \`label\` (omit for decorative icons).
CSS variables also work and cross the shadow boundary: \`--${n}-icon-size\`, \`--${n}-icon-color\`, \`--${n}-icon-color-2…\`, \`--${n}-icon-stroke-width\`.

The file contains every icon (${b.icons.length}). Need fewer? Delete entries from \`${k}_ICONS\`, or import from \`react/\` / \`angular/\` for per-icon imports.
Typings: \`${n}-icon.d.ts\`.
`
  return { [`web-component/${n}-icon.js`]: js, [`web-component/${n}-icon.d.ts`]: dts, 'web-component/README.md': readme }
}

function camelToPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
