import { changelogMarkdown, Diff } from './changelog'

export interface PullRequestInput {
  diff: Diff | null
  version: string
  /** icons in this export */
  iconCount: number
  /** export formats that were generated, e.g. ['SVG files', 'Angular 17.1+'] */
  formats: string[]
  /** icons exported with a warning (still included) */
  warnings: number
  date: string
}

const plural = (n: number, w: string) => `${n} ${w}`

/**
 * Title and description for the pull / merge request that carries an export. The description is what a reviewer needs without opening
 * Figma: what changed, whether anything breaks, which version it is, and what is still flagged.
 */
export function pullRequestText(i: PullRequestInput): { title: string; body: string } {
  const d = i.diff
  const parts = d
    ? [d.added.length && plural(d.added.length, 'added'), d.renamed.length && plural(d.renamed.length, 'renamed'), d.removed.length && plural(d.removed.length, 'removed'), (d.changed.length + d.recoloured.length) && plural(d.changed.length + d.recoloured.length, 'changed')].filter(Boolean)
    : []
  const title = d
    ? parts.length
      ? `Update icons to ${i.version}: ${parts.join(', ')}`
      : `Update icons to ${i.version}`
    : `Add icon library ${i.version} (${plural(i.iconCount, 'icons')})`

  const lines: string[] = []
  lines.push(d ? `Updates the icon library from Figma to **${i.version}** (${plural(i.iconCount, 'icons')}).` : `Adds the icon library exported from Figma, **${i.version}** (${plural(i.iconCount, 'icons')}).`)
  if (d && (d.removed.length || d.renamed.length)) {
    lines.push('', `> **Breaking:** ${d.removed.length ? `${plural(d.removed.length, 'icon(s) removed')}` : ''}${d.removed.length && d.renamed.length ? ' and ' : ''}${d.renamed.length ? `${plural(d.renamed.length, 'icon(s) renamed')} (old names keep working as deprecated aliases for one major version)` : ''}.`)
  }
  if (d) lines.push('', changelogMarkdown(d, i.version, i.date).trimEnd())
  lines.push('', `**Formats:** ${i.formats.length ? i.formats.join(', ') : 'none'}`)
  if (i.warnings) lines.push(`**Still flagged in Figma:** ${plural(i.warnings, i.warnings === 1 ? 'icon' : 'icons')} exported with warnings.`)
  lines.push('', '_Generated by Icon Library Toolkit. Review the files before merging._')
  return { title, body: lines.join('\n') + '\n' }
}
