#!/usr/bin/env node
/**
 * Regenerates THIRD_PARTY_NOTICES.md from the licence files of the packages that ship inside the built plugin.
 * Run from the repo root after `npm ci` in plugin/:   node scripts/generate-notices.mjs
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const nm = join(process.cwd(), 'plugin', 'node_modules')

/** packages bundled into build/ui.js and build/main.js (npm ls --omit=dev --all) */
const BUNDLED = [
  ['@create-figma-plugin/ui', 'https://github.com/yuanqing/create-figma-plugin', 'UI components, themes and hooks used for the plugin interface'],
  ['@create-figma-plugin/utilities', 'https://github.com/yuanqing/create-figma-plugin', 'typed messaging between the plugin UI and the Figma sandbox'],
  ['preact', 'https://github.com/preactjs/preact', 'UI runtime'],
  ['fflate', 'https://github.com/101arrowz/fflate', 'ZIP creation for exports'],
  ['hex-rgb', 'https://github.com/sindresorhus/hex-rgb', 'colour helper (dependency of @create-figma-plugin/ui)'],
  ['rgb-hex', 'https://github.com/sindresorhus/rgb-hex', 'colour helper (dependency of @create-figma-plugin/ui)'],
  ['natural-compare-lite', 'https://github.com/litejs/natural-compare-lite', 'sorting helper (dependency of @create-figma-plugin/ui)']
]

/** used only to build, test and type-check; not distributed */
const DEV = [
  ['@create-figma-plugin/build', 'MIT', 'build CLI and manifest generation'],
  ['@create-figma-plugin/tsconfig', 'MIT', 'shared TypeScript config'],
  ['@figma/plugin-typings', 'MIT', 'Figma Plugin API type definitions'],
  ['typescript', 'Apache-2.0', 'compiler / type checker'],
  ['vitest', 'MIT', 'unit tests'],
  ['happy-dom', 'MIT', 'DOM implementation for unit tests']
]

/** packages that ship no LICENSE file: the copyright line comes from the package's own README/header, the text is the standard MIT licence */
const FALLBACK_COPYRIGHT = { 'natural-compare-lite': 'Copyright (c) 2012-2015 Lauri Rooden <lauri@rooden.ee>' }
const MIT = (c) => `The MIT License (MIT)

${c}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

function licenseText(pkg) {
  for (const f of ['LICENSE', 'LICENSE.md', 'license', 'LICENSE.txt', 'license.md']) {
    const p = join(nm, pkg, f)
    if (existsSync(p)) return readFileSync(p, 'utf8').trim()
  }
  if (FALLBACK_COPYRIGHT[pkg]) return MIT(FALLBACK_COPYRIGHT[pkg])
  throw new Error(`No licence file found for ${pkg}`)
}

let out = `# Third-party notices

Icon Library Toolkit is MIT-licensed (see [LICENSE](LICENSE)). The built plugin includes the open-source software below.
Their licences require that the copyright notice and licence text accompany copies, so they are reproduced here.
This file is generated by \`scripts/generate-notices.mjs\`; do not edit the package sections by hand.

## Included in the plugin (bundled)

`
for (const [pkg, url, what] of BUNDLED) {
  const meta = JSON.parse(readFileSync(join(nm, pkg, 'package.json'), 'utf8'))
  out += `### ${pkg} ${meta.version}\n\n- Licence: ${meta.license}\n- Source: ${url}\n- Used for: ${what}\n\n\`\`\`text\n${licenseText(pkg)}\n\`\`\`\n\n`
}

out += `## Copied artwork

### Feather icons: the settings "cog" icon

The cog icon in \`plugin/src/ui/icons.tsx\` (\`CogIcon\`) uses the path data of the "settings" icon from [Feather](https://github.com/feathericons/feather).

\`\`\`text
The MIT License (MIT)

Copyright (c) 2013-2023 Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
\`\`\`

## Development tools (not distributed)

| Package | Licence | Used for |
|---|---|---|
${DEV.map(([p, l, w]) => `| ${p} | ${l} | ${w} |`).join('\n')}

TypeScript is Apache-2.0 licensed (https://www.apache.org/licenses/LICENSE-2.0). None of these tools are included in the built plugin or in exported icon libraries.

## Inspiration and references (no code copied)

- **[figma-plugin-forge](https://github.com/sallzzbr/figma-plugin-forge)** by sallzzbr (MIT): the spec-driven development method (brainstorm, design doc, plan, implement, verify) and its plugin-architecture rules (runtime split, typed messages, \`documentAccess: "dynamic-page"\`) guided how this plugin was designed. No source code from the repository is included.
- **[create-figma-plugin](https://yuanqing.github.io/create-figma-plugin/)** by Yuan Qing Lim (MIT): used as a dependency and build tool (see above).
- **Font Awesome** (https://fontawesome.com): its idea of one canonical icon name with a base class plus per-icon modifier inspired the naming scheme. No Font Awesome code, data or icons are used or included.
- The Figma Plugin API documentation and community threads linked from \`docs/\` informed the design of the problem checks and storage notes.

Icons you export with this tool are yours; the tool does not add attribution or licence requirements to generated files.
`
writeFileSync('THIRD_PARTY_NOTICES.md', out)
console.log('Wrote THIRD_PARTY_NOTICES.md')
